name: coffee_api
description: The Interface and models for an API providing access to coffee images.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  meta: ^1.9.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
