name: very_good_coffee
description: which gives the user the ability to save their favorite coffee pictures.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.0
  coffee_api:
    path: packages/coffee_api
  coffee_repository:
    path: packages/coffee_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.1
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.13



dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
