name: coffee_repository
description: A repository that handles coffee related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  coffee_api:
    path: ../coffee_api
  equatable: ^2.0.5
  json_annotation: ^4.8.0


dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
